AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD pipeline for Lambdas

Parameters:
  GitHubOwner:
    Type: String
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
    Default: main
  CodeStarConnectionArn:
    Type: String
  ArtifactBucketName:
    Type: String
  Environment:
    Type: String
  AWSAccountId:
    Type: String

Resources:

  #################################
  # Artifact Bucket
  #################################
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactBucketName

  #################################
  # CodeBuild Role
  #################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BuildAWSDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:UpdateFunctionCode
                  - s3:*
                  - logs:*
                Resource: "*"

  #################################
  # Build Project
  #################################
  BuildCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "lambda-build-${AWSAccountId}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: src/devops/codepipeline/buildspec.yaml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0

  #################################
  # Deploy Project
  #################################
  DeployCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "lambda-deploy-${AWSAccountId}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: src/devops/codepipeline/deployspec.yaml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Value: !Ref Environment

  #################################
  # CodePipeline Role
  #################################
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PipelineAWSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - codestar-connections:UseConnection
                Resource: "*"

  #################################
  # CodePipeline
  #################################
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:

        #################################
        # Source Stage
        #################################
        - Name: Source
          Actions:
            - Name: SourceFromGitHub
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepo}"
                BranchName: !Ref GitHubBranch
              OutputArtifacts:
                - Name: SourceOutput

        #################################
        # Build Stage
        #################################
        - Name: Build
          Actions:
            - Name: PackageLambdas
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref BuildCodeBuildProject

        #################################
        # Deploy Stage
        #################################
        - Name: Deploy
          Actions:
            - Name: DeployLambdas
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref DeployCodeBuildProject
