version: 0.2

env:
  variables:
    REGION: "ap-south-1"
    STACK_NAME: "file-flow-resources-dev"
    ENVIRONMENT: "dev"
 
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Updating pip and installing SAM CLI"
      - pip install --upgrade pip
      - pip install --upgrade aws-sam-cli
      - sam --version
 
  build:
    commands:
      - echo "Starting SAM build"
      - sam build --template-file devops/infra/resources.yaml
      - echo "Listing built files"
      - ls -la .aws-sam/build
 
  post_build:
    commands:
      - echo "Deploying SAM stack"
      - |
        sam deploy \
          --template-file .aws-sam/build/template.yaml \
          --stack-name ${STACK_NAME} \
          --region ${REGION} \
          --s3-bucket ${ARTIFACT_BUCKET} \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides Environment=${ENVIRONMENT} \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
 
artifacts:
  files:
    - '**/*'